name: Link check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v6

      - name: Discover broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --accept 100..=103,200..=299,403,429,500 -- ./**/*.{md,py,ipynb}
